#!/bin/sh
#
# Compile and run all pt2pt programs.
#
# As default this script runs first with two processes and second
# with four processes on the local machine. You can add more options
# to "mpiexec" on the command line, e.g.:
#
# make_pt2pt -np 6 -host sunpc1,linpc1,tyr
#
# to create six processes running on three machines.
#
#
# File: make_pt2pt			Author: S. Gross
#

TWO_PROC="Allocmem  \
Bsend  \
BsendFree  \
Buffer  \
Free \
Getcount \
Improbe \
Interf \
Iprobe \
Isend \
Mprobe \
MprobeMpich \
Probe \
Rsend \
Rsend2 \
Send \
Send2 \
Sendrecv \
SendrecvRep \
Seq \
Ssend \
Start \
Startall \
Test1 \
Test2 \
Test3 \
Testall \
Testany \
Testsome \
Waitall \
Waitany \
Waitnull \
Waitsome \
Wildcard"

NUM_PROC=$TWO_PROC

# number of processes
NP=8


echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "++++++++++++++++                        ++++++++++++++++"
echo "++++++++++++++++ mpiexec -np 2 java ... ++++++++++++++++"
echo "++++++++++++++++                        ++++++++++++++++"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
for i in $TWO_PROC; do
  echo " "
  echo " "
  echo " "
  echo =========================== $i ===========================
  mpijavac $i.java
  mpiexec -np 2 java $i
done


echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "++++"
echo "++++ mpiexec -np $NP $* java ..."
echo "++++"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
for i in $NUM_PROC; do
  echo " "
  echo " "
  echo " "
  echo =========================== $i ===========================
  mpijavac $i.java
  mpiexec -np $NP $* java $i
done

rm *.class
