#!/bin/sh
#
# Compile and run all environment programs.
#
# As default this script runs first with two processes and second
# with four processes on the local machine. You can add more options
# to "mpiexec" on the command line, e.g.:
#
# make_environment -np 6 -host sunpc1,linpc1,tyr
#
# to create six processes running on three machines.
#
#
# File: make_environment		Author: S. Gross
#

Test_Classes="OmpitestError.java \
OmpitestProgress.java \
OmpitestConfig.java"

TWO_PROC="Abort \
Attrs \
Final \
Finalized \
GetLibVersion \
GetVersion \
InitThread \
InitThreadFunneled \
InitThreadMultiple \
InitThreadSerialized \
Initialized \
IsThrMain \
Pcontrol \
Procname \
QueryThread \
Wtime"

NUM_PROC=$TWO_PROC

# number of processes
NP=8


echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "++++++++++++++++                        ++++++++++++++++"
echo "++++++++++++++++ mpiexec -np 2 java ... ++++++++++++++++"
echo "++++++++++++++++                        ++++++++++++++++"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
for i in $TWO_PROC; do
  echo " "
  echo " "
  echo " "
  echo =========================== $i ===========================
  mpijavac $i.java $Test_Classes
  mpiexec -np 2 java $i
done


echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "++++"
echo "++++ mpiexec -np $NP $* java ..."
echo "++++"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
for i in $NUM_PROC; do
  echo " "
  echo " "
  echo " "
  echo =========================== $i ===========================
#  mpijavac $i.java
  mpiexec -np $NP $* java $i
done

rm *.class
