#!/bin/sh
#
# Compile and run all communicator programs.
#
# As default this script runs first with two processes and second
# with four processes on the local machine. You can add more options
# to "mpiexec" on the command line, e.g.:
#
# make_communicator -np 6 -host sunpc1,linpc1,tyr
#
# to create six processes running on three machines.
#
#
# File: make_communicator		Author: S. Gross
#

Test_Classes="OmpitestError.java \
OmpitestProgress.java"

TWO_PROC="Attr \
CommCreateGroup \
Commdup \
CommDupWithInfo \
Commfree \
Compare \
InterComm \
Mpisplit"

NUM_PROC=$TWO_PROC

# number of processes
NP=8


echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "++++++++++++++++                        ++++++++++++++++"
echo "++++++++++++++++ mpiexec -np 2 java ... ++++++++++++++++"
echo "++++++++++++++++                        ++++++++++++++++"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
for i in $TWO_PROC; do
  echo " "
  echo " "
  echo " "
  echo =========================== $i ===========================
  mpijavac $i.java $Test_Classes
  mpiexec -np 2 java $i
done


echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "++++"
echo "++++ mpiexec -np $NP $* java ..."
echo "++++"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
for i in $NUM_PROC; do
  echo " "
  echo " "
  echo " "
  echo =========================== $i ===========================
#  mpijavac $i.java
  mpiexec -np $NP $* java $i
done

rm *.class
