#!/bin/sh
#
# Compile and run all datatype programs.
#
# As default this script runs first with two processes and second
# with four processes on the local machine. You can add more options
# to "mpiexec" on the command line, e.g.:
#
# make_datatype -np 6 -host sunpc1,linpc1,tyr
#
# to create six processes running on three machines.
#
#
# File: make_datatype			Author: S. Gross
#

TWO_PROC="Bakstr \
Bottom \
Getel \
Lbub \
Lbub2 \
Loop \
Paktest \
Pptransp \
Strangest1 \
Structsr \
Structsr2 \
Transp \
Transp2 \
Transp3 \
Transpa \
Zero1 \
Zero2 \
Zero3 \
Zero5 \
Zero6"

NUM_PROC=$TWO_PROC

# number of processes
NP=8


echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "++++++++++++++++                        ++++++++++++++++"
echo "++++++++++++++++ mpiexec -np 2 java ... ++++++++++++++++"
echo "++++++++++++++++                        ++++++++++++++++"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
for i in $TWO_PROC; do
  echo " "
  echo " "
  echo " "
  echo =========================== $i ===========================
  mpijavac $i.java
  mpiexec -np 2 java $i
done


echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "++++"
echo "++++ mpiexec -np $NP $* java ..."
echo "++++"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
for i in $NUM_PROC; do
  echo " "
  echo " "
  echo " "
  echo =========================== $i ===========================
  mpijavac $i.java
  mpiexec -np $NP $* java $i
done

rm *.class
