#!/bin/sh
#
# Compile and run all collective inter-communicator programs.
#
# As default this script runs first with two processes and second
# with four processes on the local machine. You can add more options
# to "mpiexec" on the command line, e.g.:
#
# make_collective_inter -np 6 -host sunpc1,linpc1,tyr
#
# to create six processes running on three machines.
#
#
# File: make_collective_intercomm	Author: S. Gross
#

TWO_PROC="AllgatherInter.java \
AllreduceInter.java \
AlltoallInter.java \
AlltoallvInter.java \
AlltoallwInter.java \
BarrierInter.java \
BcastInter.java \
GatherInter.java \
ReduceInter.java \
ReduceScatterInter.java \
ReduceScatterInter2.java \
ScatterInter.java \
ScattervInter.java"

NUM_PROC=$TWO_PROC

# number of processes
NP=8


echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "++++++++++++++++                        ++++++++++++++++"
echo "++++++++++++++++ mpiexec -np 2 java ... ++++++++++++++++"
echo "++++++++++++++++                        ++++++++++++++++"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
for i in $TWO_PROC; do
  echo " "
  echo " "
  echo " "
  echo =========================== $i ===========================
  mpijavac $i.java
  mpiexec -np 2 java $i
done


echo " "
echo " "
echo " "
echo " "
echo " "
echo " "
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "++++"
echo "++++ mpiexec -np $NP $* java ..."
echo "++++"
echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
for i in $NUM_PROC; do
  echo " "
  echo " "
  echo " "
  echo =========================== $i ===========================
  mpijavac $i.java
  mpiexec -np $NP $* java $i
done

rm *.class
